{{- $globalEnv := .Values.global.env | default (dict) -}}
{{- if gt (len $globalEnv) 0 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "soundspan.fullname" . }}-global-env
  labels:
    {{- include "soundspan.labels" . | nindent 4 }}
data:
  {{- range $key, $val := $globalEnv }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
